// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvFBL_AXS7oBd2OYQsH8EPMvfxDo7WwIU',
    appId: '1:899647823112:android:ea14637169dd6abc4d60bd',
    messagingSenderId: '899647823112',
    projectId: 'incasa-app-auth-321',
    storageBucket: 'incasa-app-auth-321.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Z7XQ5ounsN6e5s4sdQitw3Z517i8Ms0',
    appId: '1:899647823112:ios:8976be19fa1e59da4d60bd',
    messagingSenderId: '899647823112',
    projectId: 'incasa-app-auth-321',
    storageBucket: 'incasa-app-auth-321.firebasestorage.app',
    iosClientId: '899647823112-2lumlrqoh22fvrmpn22353k4tdck7h3q.apps.googleusercontent.com',
    iosBundleId: 'br.app.incasa.projetoIncasaApp',
  );
}
